### ISSUE TITLE
Video/demo presentation in English

### ISSUE THREAD

**Issue by kamilwylegala** [CodelyTV/cqrs-ddd-php-example#102]
Hey guys,

I found this repository today and it looks very interesting.

Can I find somewhere your video presentation in English?

Cheers!

**Comment by rgomezcasas** [comment]
Hey!

Sorry, we only did that video in Spanish, but the slides are in english (https://es.slideshare.net/CodelyTV/from-framework-coupled-code-to-microservices-through-ddd-modules-by-codelytv) :)

**Comment by kamilwylegala** [comment]
OK, thanks:) Closing issue.
