### ISSUE TITLE
Refactor Abstract Repository class to Infrastructure RepositoryNameMock class

### ISSUE THREAD

**Issue by amelendres** [CodelyTV/cqrs-ddd-php-example#103]
tests/src/Mooc/Videos/VideoModuleUnitTestCase.php

In order to mock different infrastructure (repositories, external services)

**Comment by JavierCane** [comment]
Hi @amelendres!

I'm very sorry but I don't really get what you're reporting here 😅

Could you please describe a little bit which problem do you have and how it could be improved?

Thanks!
