### ISSUE TITLE
BUG en el endpoint 

### ISSUE THREAD

**Issue by pana1990** [CodelyTV/cqrs-ddd-php-example#108]
Sigo los pasos para instalar la aplicación y al ir a la url "http://api.codelytv.localhost:8030/status" me sale el siguiente error:

![bug](https://user-images.githubusercontent.com/6630197/60993591-0ac5f480-a34f-11e9-9b84-0abd5d5dccff.png)

**Comment by JavierCane** [comment]
Buenas. Parece que (sorprendentemente) está relacionado con los cambios de https://github.com/CodelyTV/cqrs-ddd-php-example/pull/107. Lo estamos mirando en https://github.com/CodelyTV/cqrs-ddd-php-example/pull/109.

Sentimos las molestias y cualquier ayuda será más que bienvenida 😊

**Comment by JavierCane** [comment]
Arreglado con la PR https://github.com/CodelyTV/cqrs-ddd-php-example/pull/110

Era un bug de PHP en la versión 7.3.7

Gracias por el reporte!

**Comment by pana1990** [comment]
@JavierCane gracias por el patch :)
