### ISSUE TITLE
Move Responses to Application layer folder

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/cqrs-ddd-php-example#35]
In the CQRS course there has been [one doubt regarding if the `VideoResponse` was an actual domain model, or if it was a query response DTO](https://pro.codely.tv/library/cqrs-command-query-responsibility-segregation-3719e4aa/62554/path/step/33532853/discussion/98844/).

We're currently storing the responses DTOs in the Domain folder which could lead to confusion. What do you think @rgomezcasas about moving these DTOs to the Application subfolder? (In this example, the `Find` one)

**Comment by rgomezcasas** [comment]
Totally!
