### ISSUE TITLE
[Duda] ddd & doctrine

### ISSUE THREAD

**Issue by pana1990** [CodelyTV/cqrs-ddd-php-example#39]
Buenas chicos, antes de nada gran curso.

Tengo una duda de concepto con respecto a ddd y como se manejaría con doctrine:

Imaginémonos que tenemos una clase User  (que todos sabemos que no para de crecer y crecer sin darnos cuenta) y queremos dividirla en contextos para evitar que la clase tenga toda la lógica centralizada de todos los casos de uso que se puedan dar, como lo resolveríais y como manejaríais el mapeo con doctrine?

Por ejemplo  imaginémonos una red social, user tiene cierta lógica que se aplica en la autenticación (registrar, login...) y luego otra lógica que se da en la parte de amigos (agregar amigo, borrar amigo...) 

Usaríais una clase abstracta BaseUser con las propiedades básicas del usuario (userId y username) y extenderíais de ella en función del contexto?, es posible manejar esto con doctrine?

Gracias de antemano chicos ;)

**Comment by rgomezcasas** [comment]
Muy buenas, haremos un vídeo para responder a esta pregunta :)

Saludos!

**Comment by pana1990** [comment]
@rgomezcasas muchas gracias, si necesitáis ayuda aquí estoy ;)

**Comment by rgomezcasas** [comment]
Seguramente grabemos durante este mes, cualquier cosa te aviso! :)

Saludos.

**Comment by pana1990** [comment]
@rgomezcasas creo que aun no se ha grabado el video acerca de este topic no ?

**Comment by rgomezcasas** [comment]
Lo tenemos pendiente!!

Ya ves qué buenas son nuestras estimaciones 😂

**Comment by pana1990** [comment]
@rgomezcasas 😂😂, no te preocupes, estaré a la espera (si os puedo ayudar en algo por aquí me tenéis)

pd: sois unos grandes ;)

**Comment by rgomezcasas** [comment]
Gracias!! :))

**Comment by JavierCane** [comment]
Lo tenemos pendiente y lo haremos. No sé cuándo, pero lo haremos 😅

🙏 @stalebot remove `Stale` tag and do not close this issue. Thx! xD

**Comment by pana1990** [comment]
@stale reopen please :p

**Comment by pana1990** [comment]
@JavierCane este bot me tiene frito :/

**Comment by JavierCane** [comment]
jajajajjaja, mil perdones señor. Está en el backlog 😬

**Comment by pana1990** [comment]
@JavierCane puedes reabrir?

**Comment by JavierCane** [comment]
🎉 Tenemos buenas noticias

Hemos empezado a publicar el [curso DDD en PHP](https://pro.codely.tv/library/ddd-en-php/96173/about/). En él, dedicaremos una lección específicamente a temas de Doctrine, y en esta lección incluiremos un vídeo específico comentando esto 😊

Ya tienes disponible el primer bloque de lecciones, y la semana que viene publicaremos el bloque que contiene la lección sobre Doctrine.

Mil perdones por la demora y las molestias con la gestión de esta issue. Esperamos que la espera merezca la pena 🤟

¡Saludos!

**Comment by pana1990** [comment]
@JavierCane  grandisima noticia.

![image](https://user-images.githubusercontent.com/6630197/62946060-48032380-bde0-11e9-9e1c-bf861826ed65.png)

**Comment by JavierCane** [comment]
xDDD

¡Justo la publicamos mañana!

🔝👌😊👉 https://pro.codely.tv/library/ddd-en-php/96173/about/
