### ISSUE TITLE
Upgrade to CircleCI 2.0

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/cqrs-ddd-php-example#52]
We're still using the deprecated CircleCI 1.0 version for this project. It's no longer maintained, so we should upgrade to the 2.0 version.

[More info on how to upgrade](https://circleci.com/sunset1-0/)

**Comment by rgomezcasas** [comment]
Better we could migrate to GitHub Actions

**Comment by JavierCane** [comment]
Done with the latest PRs 🙂

We'll wait for Docker Compose support in GutHub Actions, but in the meanwhile, we have a working pipeline in CircleCI! https://circleci.com/gh/CodelyTV/cqrs-ddd-php-example/347
