### ISSUE TITLE
Add Git pre-push hook

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/cqrs-ddd-php-example#53]
Follow the same principles as in [the Scala API repo](https://github.com/CodelyTV/scala-http-api#pre-push-git-hook)

You can copy the very same [`pre-push` script](https://github.com/CodelyTV/scala-http-api/blob/master/doc/hooks/pre-push) just modifying the command to execute. That is, instead of calling to `sbt prep`, we should call to a command defined in the `composer.json` in order to run PhpStan, CodeSniffer, acceptance tests, and unit tests.

This issue includes the addition to the `README.md` of this `pre-push` script as in the Scala API Repo 🙂

**Comment by nidble** [comment]
Can I work on this?

**Comment by JavierCane** [comment]
For sure you can @nidble 🙂

**Comment by nidble** [comment]
Hi @JavierCane,

I successfully added phpstan, phpunit and behat. However codesniffer setup require some assumptions. One possibility is to install additional standard: https://github.com/djoos/Symfony-coding-standard, but this lead with codesniffer version (2.7 versus 3.0). 
Another solution, (spoiler alert my ❤️), from officially docs: https://symfony.com/doc/current/contributing/code/standards.html, is to install php-cs-fixer and to remove codesniffer from dev deps.

Do I miss something? What kind of approach do you prefer? :)
Thanks
Toni

**Comment by JavierCane** [comment]
Hi @nidble!

Yup, I completely agree with you. The best approach would be adding cs fixer 🙂

If you want to, I would propose to split this into 2 different PRs. One for adding php cs fixer, and a further one for adding the pre-push hook.

This way we would be able to isolate the feedback and it will also count for you as 2 PRs instead of one for the #hacktoberfest 🙂

If you want to, you can open the PR even if it's still in progress. This way we would be able to discuss about it in an early stage without waiting to have all the work done (and possibly having to change what you already had).

Thanks a lot!

**Comment by nidble** [comment]
Hi @JavierCane,

Sure! :)  But currently I'm ready for pushing "pre push" integration with php(stan & unit), and behat. In theory `composer test` commad is already supposed to be scalable (now consists of three commands).

Last but not the least implementing phpcs involve other files too (ie: circle.yml).

Let me know, the best approach you prefer! 
Thanks!

**Comment by JavierCane** [comment]
No problem then 🙂

Let's go ahead with the pre-push hook PR if you prefer so 🤘🤘🤘

**Comment by JavierCane** [comment]
PR merged. Closing issue in 3, 2, 1… 🎉
