### ISSUE TITLE
Required parameter $trustedHeaderSet missing

### ISSUE THREAD

**Issue by sdecandelario** [CodelyTV/cqrs-ddd-php-example#57]
In the file `applications/api/web/api.php` in `Request::setTrustedProxies` is needed a second parameter called `$trustedHeaderSet` of type `Request::HEADER_*`

https://github.com/CodelyTV/cqrs-ddd-php-example/blob/0e90bdd5f7f046f7c4d81c9ca92bd2868bacd5c1/applications/api/web/api.php#L14

**Comment by JavierCane** [comment]
Fixed: https://github.com/CodelyTV/cqrs-ddd-php-example/commit/6858b5725e583936513901c01f088573d827c3b6
