### ISSUE TITLE
Create Request/Response DTOs for Application Services

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/cqrs-ddd-php-example#66]
# What

Instead of instantiating the Value Objects directly from the controller, we should instantiate a DTO such as `SignUpUserRequest` and pass it to the Application Service.

The Application Services intended for querying data, we should return also a DTO such as `UserResponse`.

# Why

This way we:

* Avoid coupling our entry points to the internal details on how we model out our domain (`UserId` value objects and so on).
* Leave the code on the Hexagonal Architecture approach closer to what we'll do while evolving to an architecture applying CQRS concepts. We will only need to:
    * Replace the `XxxRequest` by their corresponding `XxxCommand`, 
    * Send the commands to the Command Bus instead of directly calling the Application Service
    * Implement the Command Handler in order to extract each one of the scalar values from the Command, convert them to Value Object instances, and call to the Application Service
    * Modify the Application Service in order to directly receive the Value Objects instead of the `XxxRequest`

**Comment by JavierCane** [comment]
Thoughts @rgomezcasas?

**Comment by rgomezcasas** [comment]
Agree, @JavierCane :P

When we'll have time we should do that, but I don't see this as a priority :)

**Comment by JavierCane** [comment]
Totally 🙂

I'll leave it as a living issue then (the Stale bot had prepared the bullet to kill it, but we'll make it resist) 💪

xD

**Comment by rgomezcasas** [comment]
![image](https://user-images.githubusercontent.com/1331435/54436336-9e394100-4732-11e9-8134-edb2c15be14a.png)
